export {
  CAMPAIGN_ABI,
  ERC20_ABI,
  FACTORY_ABI,
  FACTORY_ADDRESSES,
  DEFAULT_FACTORY_ADDRESS as FACTORY_ADDRESS,
  DEFAULT_PLATFORM_WALLET as PLATFORM_WALLET,
  DEFAULT_USDC_ADDRESS as USDC_ADDRESS,
  getFactoryAddress,
  getFundingTokenAddress,
  getFundingTokenConfig,
  getFundingTokenDecimals,
  getFundingTokenSymbol,
  getPlatformWallet,
  getUsdcAddress,
} from "./config/contracts";
